import cloudTexture from "@/assets/cloud.png";
import hillTexture from "@/assets/hill.png";
import fireTexture from "@/assets/fire.png";

export const config = {
  game: {
    helpers: false,
    speed: 2,
  },
  directional: {
    enabled: true,
    helper: false,
    intensity: 2,
  },
  blocks: {
    helper: false,
    size: 30,
    spacing: 150,
  },
  player: {
    helper: true,
    speed: 25,
    maxJump: 100,
    heightOffset: 10,
    collisionThreshold: 38,
    jump: {
      height: 100,
      duration: 1000,
      isActive: false,
      velocity: 0,
      startTime: 0,
    },
  },
  backgrounds: {
    layers: [
      {
        texture: cloudTexture,
        speed: 2,
        size: 200,
        ratio: 2.5,
        yPosition: 130,
        xVariation: 300,
        yVariation: 20,
        zPosition: -300,
        count: 4,
        spacing: 600,
        opacity: 0.5,
      },
      {
        texture: cloudTexture,
        speed: 2,
        size: 200,
        ratio: 2.5,
        yPosition: 150,
        xVariation: 300,
        yVariation: 20,
        zPosition: -100,
        count: 3,
        spacing: 600,
        opacity: 0.5,
      },
      {
        texture: cloudTexture,
        speed: 2,
        size: 200,
        ratio: 2.5,
        yPosition: 140,
        xVariation: 300,
        yVariation: 10,
        zPosition: 20,
        count: 3,
        spacing: 600,
        opacity: 0.7,
      },
      {
        texture: hillTexture,
        speed: 2,
        size: 1000,
        ratio: 1,
        xVariation: 100,
        yPosition: 70,
        yVariation: 70,
        zPosition: -800,
        count: 10,
        spacing: 1000,
        opacity: 0.5,
      },
      {
        texture: fireTexture,
        speed: 2,
        size: 12,
        ratio: 1,
        xVariation: 100,
        yPosition: 8,
        yVariation: 0,
        zVariation: 50,
        zPosition: -70,
        count: 10,
        spacing: 100,
        opacity: 0.4,
      },
      {
        texture: fireTexture,
        speed: 2,
        size: 12,
        ratio: 1,
        xVariation: 100,
        yPosition: 8,
        yVariation: 0,
        zVariation: 30,
        zPosition: 100,
        count: 10,
        spacing: 300,
        opacity: 0.4,
      },
    ],
  },
};

// Game status enum-like values
export const GAME_STATUS = {
  START: "start",
  PLAYING: "playing",
  GAME_OVER: "gameOver",
} as const;
