[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[build.environment]
  # Ensure FFmpeg is available in the build environment
  NODE_VERSION = "22"

# For FFmpeg support, you might need to use a custom build image
# or include FFmpeg as a static binary in your functions
